import '../../models/safety_item_model.dart';

/// Aura Pregnancy - Besin, Kozmetik ve Bitkisel Güvenlik Radarı Veritabanı
class SafetyRadarData {
  static const List<SafetyItem> items = [
    // --- GIDALAR: GÜVENLİ (YEŞİL) ---
    SafetyItem(
      id: 'food_cooked_salmon',
      title: 'İyi Pişmiş Somon',
      titleEn: 'Well-Cooked Salmon',
      category: SafetyCategory.food,
      level: SafetyLevel.safe,
      summary: 'Gönül rahatlığıyla haftada 2-3 porsiyon tüketilebilir.',
      summaryEn: 'Can be safely consumed 2-3 servings per week.',
      medicalReason: 'Yüksek Omega-3 (DHA/EPA) bebeğin beyin ve retina gelişimini destekler. Düşük cıvalı balıktır.',
      medicalReasonEn: 'High Omega-3 (DHA/EPA) supports fetal brain and retinal development. It is a low-mercury fish.',
      alternativeSuggestion: 'Fırında zeytinyağlı ve limonlu pişirebilirsiniz.',
      alternativeSuggestionEn: 'Bake with olive oil and fresh lemon.',
      emoji: '🐟',
    ),
    SafetyItem(
      id: 'food_pasteurized_cheese',
      title: 'Pastörize Beyaz Peynir / Kaşar',
      titleEn: 'Pasteurized White Cheese / Cheddar',
      category: SafetyCategory.food,
      level: SafetyLevel.safe,
      summary: 'Pastörize sütten üretildiği sürece güvenlidir.',
      summaryEn: 'Completely safe as long as made from pasteurized milk.',
      medicalReason: 'Kalsiyum ve protein deposudur. Pastörizasyon listeria bakterisi riskini sıfırlar.',
      medicalReasonEn: 'Rich in calcium and protein. Pasteurization eliminates listeria bacteria risk.',
      emoji: '🧀',
    ),
    SafetyItem(
      id: 'food_pasteurized_yogurt',
      title: 'Yoğurt & Kefir',
      titleEn: 'Yogurt & Kefir',
      category: SafetyCategory.food,
      level: SafetyLevel.safe,
      summary: 'Mükemmel probiyotik ve kalsiyum kaynağıdır.',
      summaryEn: 'Excellent source of probiotics and bioavailable calcium.',
      medicalReason: 'Gebelikte bağırsak mikrobiyotasını korur, kabızlığı önler.',
      medicalReasonEn: 'Supports gut microbiota during pregnancy and prevents constipation.',
      emoji: '🥣',
    ),
    SafetyItem(
      id: 'food_hard_boiled_egg',
      title: 'Tam Pişmiş Yumurta',
      titleEn: 'Hard-Boiled Egg',
      category: SafetyCategory.food,
      level: SafetyLevel.safe,
      summary: 'Sarısı ve beyazı katılaşana kadar pişirilmelidir.',
      summaryEn: 'Must be cooked until both yolk and white are completely firm.',
      medicalReason: 'Zengin kolin içeriği fetal nöral tüp ve beyin gelişiminde kilit rol oynar.',
      medicalReasonEn: 'Rich choline content plays a critical role in fetal neural tube and brain development.',
      emoji: '🥚',
    ),
    SafetyItem(
      id: 'food_avocado',
      title: 'Avokado',
      titleEn: 'Avocado',
      category: SafetyCategory.food,
      level: SafetyLevel.safe,
      summary: 'Sağlıklı yağlar ve folat açısından süper besindir.',
      summaryEn: 'Superfood packed with healthy monounsaturated fats and folate.',
      medicalReason: 'Potasyum içeriği bacak kramplarını azaltmaya yardımcı olur.',
      medicalReasonEn: 'High potassium content helps prevent and relieve pregnancy leg cramps.',
      emoji: '🥑',
    ),
    SafetyItem(
      id: 'food_oats',
      title: 'Yulaf Ezmesi',
      titleEn: 'Rolled Oats',
      category: SafetyCategory.food,
      level: SafetyLevel.safe,
      summary: 'Kompleks karbonhidrat ve lif zenginidir.',
      summaryEn: 'Rich in complex carbohydrates and soluble fiber.',
      medicalReason: 'Kan şekerini dengeler, gebelik şekeri (gestasyonel diyabet) riskini azaltır.',
      medicalReasonEn: 'Balances blood sugar and lowers the risk of gestational diabetes.',
      emoji: '🌾',
    ),

    // --- GIDALAR: ÖLÇÜLÜ / ŞARTLI (SARI) ---
    SafetyItem(
      id: 'food_canned_tuna',
      title: 'Konserve Ton Balığı',
      titleEn: 'Canned Tuna (Light)',
      category: SafetyCategory.food,
      level: SafetyLevel.moderate,
      summary: 'Haftada en fazla 140-170 gram (1 küçük kutu) ile sınırlandırın.',
      summaryEn: 'Limit to max 140-170g (1 small can) per week.',
      medicalReason: 'Hafif cıva birikimi riski taşır. Açık renkli (light) ton balığı tercih edin.',
      medicalReasonEn: 'Carries moderate mercury accumulation risk. Choose canned light tuna over albacore.',
      alternativeSuggestion: 'Taze hamsi, sardalya veya somon tercih edebilirsiniz.',
      alternativeSuggestionEn: 'Opt for fresh anchovy, sardine, or wild salmon.',
      emoji: '🥫',
    ),
    SafetyItem(
      id: 'food_coffee',
      title: 'Kahve & Kafein',
      titleEn: 'Coffee & Caffeine',
      category: SafetyCategory.food,
      level: SafetyLevel.moderate,
      summary: 'Günlük kafein tüketimi 200 mg altında kalmalıdır (1 kupa filtre kahve veya 1 fincan Türk kahvesi).',
      summaryEn: 'Daily caffeine intake must stay below 200 mg (1 mug drip coffee or 1 cup espresso).',
      medicalReason: 'Aşırı kafein plasentayı geçerek fetal kalp ritmini hızlandırabilir ve demir emilimini azaltır.',
      medicalReasonEn: 'Excess caffeine crosses the placenta, accelerates fetal heart rate, and hinders iron absorption.',
      alternativeSuggestion: 'Kafeinsiz (Decaf) kahve veya ılık ballı süt tercih edin.',
      alternativeSuggestionEn: 'Switch to Swiss-water decaf coffee or warm milk.',
      emoji: '☕',
    ),
    SafetyItem(
      id: 'food_green_tea',
      title: 'Yeşil Çay',
      titleEn: 'Green Tea',
      category: SafetyCategory.food,
      level: SafetyLevel.moderate,
      summary: 'Günde en fazla 1 fincan içilmelidir.',
      summaryEn: 'Limit to maximum 1 cup per day.',
      medicalReason: 'İçerdiği EGCG kateşini folik asit emilimini kısmen baskılayabilir.',
      medicalReasonEn: 'Contains EGCG catechins which may partially inhibit folic acid absorption.',
      alternativeSuggestion: 'Ihlamur veya rooibos çayı güvenlidir.',
      alternativeSuggestionEn: 'Linden or caffeine-free rooibos tea are completely safe.',
      emoji: '🍵',
    ),
    SafetyItem(
      id: 'food_parsley',
      title: 'Maydanoz (Çiğ Salata)',
      titleEn: 'Parsley (Culinary Garnish)',
      category: SafetyCategory.food,
      level: SafetyLevel.moderate,
      summary: 'Yemek ve salatalarda süsleme olarak güvenlidir; kaynatıp suyunu içmekten kaçının.',
      summaryEn: 'Safe in salads and cooked dishes; strictly avoid boiled concentrated parsley tea.',
      medicalReason: 'Yoğun maydanoz suyu konsantresi apiole maddesi nedeniyle rahim kasılmalarını tetikleyebilir.',
      medicalReasonEn: 'Concentrated apiol in boiled parsley extracts can stimulate uterine contractions.',
      emoji: '🌿',
    ),

    // --- GIDALAR: SAKINCALI (KIRMIZI) ---
    SafetyItem(
      id: 'food_raw_meat_cigkofte',
      title: 'Çiğ Köfte / Çiğ Et',
      titleEn: 'Raw Meat / Beef Tartare',
      category: SafetyCategory.food,
      level: SafetyLevel.unsafe,
      summary: 'Etli çiğ köfte, tartar ve az pişmiş biftek kesinlikle tüketilmemelidir.',
      summaryEn: 'Raw minced meat, tartare, and undercooked steak must be strictly avoided.',
      medicalReason: 'Toksoplazmozis ve Salmonella enfeksiyonu riski taşır; bebekte görme ve beyin hasarına yol açabilir.',
      medicalReasonEn: 'High risk of toxoplasmosis and salmonella; can cause congenital eye and brain complications.',
      alternativeSuggestion: 'Etsiz cevizli çiğ köfte veya iyi pişmiş köfte güvenle tüketilebilir.',
      alternativeSuggestionEn: 'Meatless walnut köfte or thoroughly cooked grilled meatballs are safe.',
      emoji: '🥩',
    ),
    SafetyItem(
      id: 'food_sushi_raw_fish',
      title: 'Çiğ Suşi / Çiğ Deniz Ürünleri',
      titleEn: 'Raw Sushi / Raw Seafood',
      category: SafetyCategory.food,
      level: SafetyLevel.unsafe,
      summary: 'Çiğ somon, ton balığı, midye dolma ve istiridye tüketilmemelidir.',
      summaryEn: 'Raw sashimi, oysters, clams, and stuffed mussels must not be eaten.',
      medicalReason: 'Listeria monocytogenes bakterisi ve parazit riski düşüğe ve erken doğuma neden olabilir.',
      medicalReasonEn: 'Listeria and marine parasite risks can lead to miscarriage or preterm labor.',
      alternativeSuggestion: 'Pişmiş karidesli sushi roll veya sebzeli sushi (Avocado Roll) tercih edebilirsiniz.',
      alternativeSuggestionEn: 'Choose fully cooked shrimp roll or vegetable avocado sushi.',
      emoji: '🍣',
    ),
    SafetyItem(
      id: 'food_unpasteurized_cheese',
      title: 'Pastörize Edilmemiş Peynirler (Rokfor, Brie, Köy Peyniri)',
      titleEn: 'Unpasteurized Soft Cheeses (Brie, Roquefort)',
      category: SafetyCategory.food,
      level: SafetyLevel.unsafe,
      summary: 'Çiğ sütten yapılan yumuşak küflü peynirlerden kaçınılmalıdır.',
      summaryEn: 'Avoid soft, mold-ripened cheeses made from raw or unpasteurized milk.',
      medicalReason: 'Pastörize edilmemiş süt listerioz enfeksiyonunun bir numaralı kaynağıdır.',
      medicalReasonEn: 'Unpasteurized dairy is the primary vector for perinatal listeriosis.',
      alternativeSuggestion: 'Paketli pastörize kaşar veya sert gouda peyniri tüketin.',
      alternativeSuggestionEn: 'Enjoy packaged pasteurized cheddar, mozzarella, or hard gouda.',
      emoji: '🧀',
    ),
    SafetyItem(
      id: 'food_deli_meat',
      title: 'Çiğ Şarküteri (Salam, Sosis, Çiğ Sucuk)',
      titleEn: 'Deli Meats (Cold Salami, Prosciutto, Hot Dogs)',
      category: SafetyCategory.food,
      level: SafetyLevel.unsafe,
      summary: 'İyice kızartılmadan (en az 75°C) çiğ veya soğuk sandviç içinde yenmemelidir.',
      summaryEn: 'Do not eat cold or uncooked unless steaming hot (heated above 75°C / 165°F).',
      medicalReason: 'İşlenmiş etler listeria bakterisi ve yüksek nitrit içerir.',
      medicalReasonEn: 'Processed cold meats can harbor listeria bacteria and contain concentrated nitrites.',
      alternativeSuggestion: 'Tavada tamamen pişmiş sucuk veya haşlanmış hindi göğsü yiyebilirsiniz.',
      alternativeSuggestionEn: 'Eat well-browned skillet-cooked meats or fresh oven-roasted turkey breast.',
      emoji: '🥓',
    ),

    // --- BİTKİ ÇAYLARI VE TAKVİYELER ---
    SafetyItem(
      id: 'herb_linden',
      title: 'Ihlamur & Melisa Çayı',
      titleEn: 'Linden & Lemon Balm Tea',
      category: SafetyCategory.herb,
      level: SafetyLevel.safe,
      summary: 'Günde 1-2 fincan ılık olarak güvenle içilebilir.',
      summaryEn: 'Safely enjoy 1-2 warm cups daily.',
      medicalReason: 'Mideyi yatıştırır, doğal sakinlik verir ve boğazı yumuşatır.',
      medicalReasonEn: 'Soothes digestion, offers mild calming relief, and relieves mild throat irritation.',
      emoji: '🌼',
    ),
    SafetyItem(
      id: 'herb_ginger',
      title: 'Taze Zencefil Çayı',
      titleEn: 'Fresh Ginger Tea',
      category: SafetyCategory.herb,
      level: SafetyLevel.safe,
      summary: 'Günde 1 fincan ılık zencefil limon çayı güvenlidir.',
      summaryEn: '1 cup of warm ginger lemon tea daily is safe and beneficial.',
      medicalReason: 'Sabah bulantılarını (morning sickness) hafifletmede klinik olarak kanıtlanmıştır.',
      medicalReasonEn: 'Clinically proven to significantly alleviate morning sickness and nausea.',
      emoji: '🫚',
    ),
    SafetyItem(
      id: 'herb_sage',
      title: 'Adaçayı (Sage)',
      titleEn: 'Sage Tea (Salvia)',
      category: SafetyCategory.herb,
      level: SafetyLevel.unsafe,
      summary: 'Hamilelik süresince adaçayı içilmemelidir.',
      summaryEn: 'Strictly avoid drinking sage tea throughout pregnancy.',
      medicalReason: 'Tujon (thujone) bileşiği içerir; rahim kasılmalarını uyarabilir ve tansiyonu yükseltebilir.',
      medicalReasonEn: 'Contains concentrated thujone, which can trigger uterine spasms and elevate blood pressure.',
      alternativeSuggestion: 'Papatya veya ıhlamur çayı içiniz.',
      alternativeSuggestionEn: 'Drink gentle chamomile or linden flower tea.',
      emoji: '🌱',
    ),
    SafetyItem(
      id: 'herb_senna',
      title: 'Sinameki Çayı',
      titleEn: 'Senna Tea (Laxative Herbs)',
      category: SafetyCategory.herb,
      level: SafetyLevel.unsafe,
      summary: 'Zayıflama ve form çaylarında sık bulunan sinamekiden uzak durun.',
      summaryEn: 'Avoid senna and harsh herbal detox teas completely.',
      medicalReason: 'Şiddetli bağırsak kramplarına ve rahim kasılmalarına sebep olabilir.',
      medicalReasonEn: 'Causes potent intestinal cramping that may reflexively stimulate uterine contractions.',
      alternativeSuggestion: 'Kabızlık için kuru erik hoşafı ve bol su tüketin.',
      alternativeSuggestionEn: 'Relieve constipation with stewed prunes, chia pudding, and plenty of water.',
      emoji: '🍂',
    ),

    // --- CİLT BAKIMI & KOZMETİK: GÜVENLİ (YEŞİL) ---
    SafetyItem(
      id: 'skin_hyaluronic_acid',
      title: 'Hyaluronik Asit',
      titleEn: 'Hyaluronic Acid',
      category: SafetyCategory.skincare,
      level: SafetyLevel.safe,
      summary: 'Gebelikte %100 güvenlidir, nem bariyerini güçlendirir.',
      summaryEn: '100% safe during pregnancy, restores skin barrier hydration.',
      medicalReason: 'Vücutta doğal olarak bulunan bir moleküldür, sistemik emilim göstermez.',
      medicalReasonEn: 'A naturally occurring bodily substance with zero systemic blood absorption.',
      emoji: '💧',
    ),
    SafetyItem(
      id: 'skin_vitamin_c',
      title: 'C Vitamini Serumu',
      titleEn: 'Vitamin C Serum',
      category: SafetyCategory.skincare,
      level: SafetyLevel.safe,
      summary: 'Leke oluşumunu önlemede güvenli ve etkilidir.',
      summaryEn: 'Safe and highly effective for preventing hyperpigmentation.',
      medicalReason: 'Hamilelik maskesi (melazma) oluşumuna karşı güçlü ve güvenli antioksidandır.',
      medicalReasonEn: 'Potent, safe antioxidant that guards against pregnancy mask (melasma).',
      emoji: '🍊',
    ),
    SafetyItem(
      id: 'skin_mineral_sunscreen',
      title: 'Mineral Güneş Koruyucu (Çinko Oksit / Titanyum Dioksit)',
      titleEn: 'Mineral Sunscreen (Zinc Oxide / Titanium Dioxide)',
      category: SafetyCategory.skincare,
      level: SafetyLevel.safe,
      summary: 'Fiziksel filtreli koruyucular hamilelikte altın standarttır.',
      summaryEn: 'Physical mineral filters are the gold standard for pregnancy sun protection.',
      medicalReason: 'Deri altına emilmez, ayna gibi ışığı yansıtarak melazmayı engeller.',
      medicalReasonEn: 'Does not penetrate the dermis; creates a surface shield reflecting UV rays.',
      emoji: '☀️',
    ),
    SafetyItem(
      id: 'skin_bakuchiol',
      title: 'Bakuchiol (Bitkisel Retinol Alternatifi)',
      titleEn: 'Bakuchiol (Plant-Based Retinol Alternative)',
      category: SafetyCategory.skincare,
      level: SafetyLevel.safe,
      summary: 'Retinoid yerine kullanabileceğiniz güvenli bitkisel alternatiftir.',
      summaryEn: 'Safe botanical alternative to retinoids for fine lines and elasticity.',
      medicalReason: 'Hücre yenilenmesini uyarır ancak fetal gelişim üzerinde toksik etkisi yoktur.',
      medicalReasonEn: 'Stimulates collagen synthesis without any teratogenic or embryotoxic effects.',
      emoji: '🌸',
    ),

    // --- CİLT BAKIMI: ÖLÇÜLÜ / ŞARTLI (SARI) ---
    SafetyItem(
      id: 'skin_salicylic_acid',
      title: 'Salisilik Asit (BHA)',
      titleEn: 'Salicylic Acid (BHA)',
      category: SafetyCategory.skincare,
      level: SafetyLevel.moderate,
      summary: '%2 veya daha düşük konsantrasyonda lokal bölgesel kullanım genellikle güvenlidir.',
      summaryEn: 'Topical spot treatment at 2% or lower concentration is generally considered safe.',
      medicalReason: 'Yüksek doz oral veya geniş alan vücut peelingleri aspirin türevi olduğu için riskli olabilir.',
      medicalReasonEn: 'Related to aspirin; avoid high-concentration full-body peels or oral ingestion.',
      alternativeSuggestion: 'Laktik asit veya Azelaik asit (%10) daha güvenli bir eksfoliyandır.',
      alternativeSuggestionEn: 'Azelaic acid (10%) or mild lactic acid are safer daily alternatives.',
      emoji: '🧴',
    ),
    SafetyItem(
      id: 'skin_glycolic_acid',
      title: 'Glikolik Asit (AHA)',
      titleEn: 'Glycolic Acid (AHA)',
      category: SafetyCategory.skincare,
      level: SafetyLevel.moderate,
      summary: '%7 ve altındaki düşük konsantrasyonlu tonikler ölçülü kullanılabilir.',
      summaryEn: 'Low concentrations (7% or less) can be used moderately.',
      medicalReason: 'Cilt bariyeri hassaslaştığı için lekelenmeyi artırabilir, güneşe dikkat edilmelidir.',
      medicalReasonEn: 'May increase photosensitivity and trigger melasma; pair with strict SPF.',
      emoji: '✨',
    ),

    // --- CİLT BAKIMI: SAKINCALI (KIRMIZI) ---
    SafetyItem(
      id: 'skin_retinoids',
      title: 'Retinol / Tretinoin / A Vitamini Türevleri',
      titleEn: 'Retinoids / Retinol / Tretinoin (Vitamin A)',
      category: SafetyCategory.skincare,
      level: SafetyLevel.unsafe,
      summary: 'Krem, serum ve hap formu gebelikte KESİNLİKLE bırakılmalıdır.',
      summaryEn: 'Topical creams, serums, and oral medications must be STRICTLY avoided.',
      medicalReason: 'Yüksek doz A vitamini türevleri fetal malformasyon (teratojenik etki) ile doğrudan ilişkilidir.',
      medicalReasonEn: 'High-dose Vitamin A derivatives have well-documented teratogenic risks for fetal organs.',
      alternativeSuggestion: 'Bakuchiol, Niasinamid (%5) veya Hyaluronik asit kullanabilirsiniz.',
      alternativeSuggestionEn: 'Switch to Bakuchiol, 5% Niacinamide, or pure Hyaluronic Acid.',
      emoji: '🚫',
    ),
    SafetyItem(
      id: 'skin_hydroquinone',
      title: 'Hidrokinon (Leke Kremi)',
      titleEn: 'Hydroquinone (Skin Lightening)',
      category: SafetyCategory.skincare,
      level: SafetyLevel.unsafe,
      summary: 'Leke açıcı kremlerde bulunan hidrokinondan kaçınılmalıdır.',
      summaryEn: 'Avoid prescription skin-bleaching creams containing hydroquinone.',
      medicalReason: 'Ciltten yüksek oranda (%35-45) sistemik dolaşıma geçer.',
      medicalReasonEn: 'Exhibits unusually high systemic absorption through maternal skin (up to 45%).',
      alternativeSuggestion: 'C Vitamini ve Azelaik asit leke için güvenlidir.',
      alternativeSuggestionEn: 'Use Vitamin C serum and Azelaic acid for safe pregnancy brightening.',
      emoji: '⚠️',
    ),
    SafetyItem(
      id: 'skin_chemical_sunscreen',
      title: 'Oksibenzon (Kimyasal Güneş Filtresi)',
      titleEn: 'Oxybenzone (Chemical UV Filter)',
      category: SafetyCategory.skincare,
      level: SafetyLevel.unsafe,
      summary: 'Oxybenzone içeren kimyasal filtreli güneş kremleri yerine mineral filtre tercih edilmelidir.',
      summaryEn: 'Avoid sunscreens with oxybenzone; opt for non-nano zinc oxide mineral SPF.',
      medicalReason: 'Hormonal dengeyi ve plasental dolaşımı etkileyebilecek moleküler yapıya sahiptir.',
      medicalReasonEn: 'Acts as an endocrine disruptor and penetrates maternal-placental circulation.',
      alternativeSuggestion: 'Çinko oksit (Zinc Oxide) bazlı mineral kremler kullanın.',
      alternativeSuggestionEn: 'Select 100% Zinc Oxide or Titanium Dioxide physical sunscreens.',
      emoji: '🏖️',
    ),
  ];

  static List<SafetyItem> search(String query, {SafetyCategory? category, SafetyLevel? level}) {
    final cleanQuery = query.trim().toLowerCase();
    return items.where((item) {
      if (category != null && item.category != category) return false;
      if (level != null && item.level != level) return false;
      if (cleanQuery.isEmpty) return true;
      return item.title.toLowerCase().contains(cleanQuery) ||
          (item.titleEn?.toLowerCase().contains(cleanQuery) ?? false) ||
          item.summary.toLowerCase().contains(cleanQuery) ||
          (item.summaryEn?.toLowerCase().contains(cleanQuery) ?? false) ||
          item.medicalReason.toLowerCase().contains(cleanQuery) ||
          (item.medicalReasonEn?.toLowerCase().contains(cleanQuery) ?? false) ||
          (item.alternativeSuggestion?.toLowerCase().contains(cleanQuery) ?? false) ||
          (item.alternativeSuggestionEn?.toLowerCase().contains(cleanQuery) ?? false);
    }).toList();
  }
}
